//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.GaussMethod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GaussMethod.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartGauss", ReplyAction="http://tempuri.org/IService/StartGaussResponse")]
        double[] StartGauss(double[] value, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartGauss", ReplyAction="http://tempuri.org/IService/StartGaussResponse")]
        System.Threading.Tasks.Task<double[]> StartGaussAsync(double[] value, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetObrMatrix", ReplyAction="http://tempuri.org/IService/GetObrMatrixResponse")]
        double[] GetObrMatrix(double[] value, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetObrMatrix", ReplyAction="http://tempuri.org/IService/GetObrMatrixResponse")]
        System.Threading.Tasks.Task<double[]> GetObrMatrixAsync(double[] value, int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TestApp.GaussMethod.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<TestApp.GaussMethod.IService>, TestApp.GaussMethod.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double[] StartGauss(double[] value, int size) {
            return base.Channel.StartGauss(value, size);
        }
        
        public System.Threading.Tasks.Task<double[]> StartGaussAsync(double[] value, int size) {
            return base.Channel.StartGaussAsync(value, size);
        }
        
        public double[] GetObrMatrix(double[] value, int size) {
            return base.Channel.GetObrMatrix(value, size);
        }
        
        public System.Threading.Tasks.Task<double[]> GetObrMatrixAsync(double[] value, int size) {
            return base.Channel.GetObrMatrixAsync(value, size);
        }
    }
}
